# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
    - name: Checkout Branch
      uses: actions/checkout@v1
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        version: 14
    - name: Build Extension
      run: |
        npm install
        npm run compile
    - name: Package Extension
      run: |
        npm install -g vsce
        vsce package
        mkdir vsix
        mv *.vsix vsix
    - name: Archive Extension
      uses: actions/upload-artifact@v1
      with:
        name: vsix
        path: vsix
